### ISSUE TITLE
Flatpak Build Bundle hangs

### ISSUE THREAD

**Issue by Alee14** [pobthebuilder/resolve-flatpak#18]
I ran `flatpak build-bundle repo resolve.flatpak com.blackmagic.Resolve` for 29 minutes and nothing happened. Is there something that I missed?

**Comment by McCrafterIV** [comment]
The build process was previously without console output. Depending on which version of the repository you tried to build, this may apply to you. Building, at least for me, took a long time (definitely over half an hour) so just be patient for a couple of hours.
