### ISSUE TITLE
[Dependency] error: org.freedesktop.Sdk/x86_64/22.08 not installed

### ISSUE THREAD

**Issue by kernelb00t** [pobthebuilder/resolve-flatpak#23]
Running `flatpak-builder --force-clean --repo=repo build-dir com.blackmagic.Resolve.yaml` throws this on latest Arch :
```
error: org.freedesktop.Sdk/x86_64/22.08 not installed
Failed to init: Unable to find sdk org.freedesktop.Sdk version 22.08
```
Installing `org.freedesktop.Sdk` with `flatpak install org.freedesktop.Sdk` beforehand makes sure the SDK is installed and up to date.

**Comment by ShiftHackZ** [comment]
I have run into the same problem, the solution [here](https://github.com/flatpak/flatpak/issues/4724) helped to fix the issue:

1. Remove already installed platform

```bash
flatpak remove --user org.freedesktop.Platform
```

2. Add flathub system-wide

```bash
sudo flatpak remote-add --if-not-exists --system flathub \                     
  https://flathub.org/repo/flathub.flatpakrepo
```
3. Run system-wide `org.freedesktop.Platform ` installation, while installing make sure to install the correct 22.08 version

```bash
sudo flatpak install --verbose org.freedesktop.Platform 
```

Then cd to the repo folder, and try to re-run:

```bash
flatpak-builder --force-clean --repo=repo build-dir com.blackmagic.Resolve.yaml
```
