### ISSUE TITLE
Flatpak instance is left in the background after exiting, possibly preventing future launches

### ISSUE THREAD

**Issue by Commodoreprime** [pobthebuilder/resolve-flatpak#24]
After force quitting Resolve from the command line or by exiting via the UI, the instance is left hanging(?).

EDIT: Neglected to mention this initially (didn't think to test) but these issues happen during the project selection screen, if a project is opened then is exited via the UI, the instance does not appear to be left hanging after Resolve exits. Unsure if this discredits the issue but it still hangs if force quit via command line for example.

For example after running `flatpak run --branch=master --arch=x86_64 --file-forwarding com.blackmagic.Resolve` from the command line three times results in the following `flatpak ps` output:
```
Instance   PID   Application            Runtime
1133055776 11269 com.blackmagic.Resolve org.freedesktop.Platform
2666668900 10913 com.blackmagic.Resolve org.freedesktop.Platform
477257514  10550 com.blackmagic.Resolve org.freedesktop.Platform
```

(note that the `--command=/app/bin/resolve.sh` flag does not change anything)

Additionally, if Resolve exited unexpectedly (i.e. force exiting) there would be an additional issue where launching future instances of Resolve would result in nothing happening, essentially the output hanging after:
```
ActCCMessage Already in Table: Code= c005, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= c006, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= c007, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= 2282, Mode=  0, Level=  0, CmdKey= 8, Option= 0
PnlMsgActionStringAdapter Already in Table: Code= 615e, Mode=  0, Level=  0, CmdKey= -1, Option= 0
log4cxx: No appender could be found for logger (BtCommon).
log4cxx: Please initialize the log4cxx system properly.
```

I'm not sure if this is a Flatpak runtime issue or just Resolve jank but regardless, fairly annoying! Best solution I've found in the meantime to mitigate this is to run `flatpak kill com.blackmagic.Resolve`.

**Comment by SzczurekYT** [comment]
Just want to confirm that sometimes resolve stays in the background. Mainly when you quit from the project manager, but not only.

**Comment by Commodoreprime** [comment]
Sorry for getting back months later...

The issue seems to have fixed itself since then. I don't exactly know what changed so I'm just going to blame the state of my system at the time lol, I'll close this issue.
