### ISSUE TITLE
Studio version being installed, even when `_product="davinci-resolve`

### ISSUE THREAD

**Issue by poperigby** [pobthebuilder/resolve-flatpak#3]
Hi, thanks for making this Flatpak. I was having a little bit of trouble with it though.

I opened `com.blackmagic.Resolve.yaml` and I changed line 152 to be `_product="davinci-resolve"` instead of `_product="davinci-resolve-studio"`. Then I ran `flatpak-builder --user --install --force-clean build-dir com.blackmagic.Resolve.yaml`. When I launched Davinci Resolve, it oddly enough gave me a popup asking for my product key, and the pop said "Davinci Resolve Studio". 

Did I do something wrong? I noticed that `_product` only shows up once in the manifest, so is that variable being used incorrectly?

**Comment by arbv** [comment]
Happened to me as well. One needs to change "davinci-resolve-studio" to "davinci-resolve" in the JSON query as well.

**Comment by arbv** [comment]
Honestly, I would suggest to split the configuration in order to have one for the free version (com.blackmagic.Resolve) and Studion (com.blackmagic.ResolveStudio).

That would make the editing step unnecessary.

**Comment by pobthebuilder** [comment]
yeah, i suck. i fixed it now in the latest version of the package and split resolve + resolve studio into their own yaml files, broke the shell scripts out into their own files and generally cleaned up a lot of things. i also added appstream metainfo data as a bonus and a bunch of other stuff. give the latest revision a whirl.
