### ISSUE TITLE
won't start or something

### ISSUE THREAD

**Issue by koloved** [pobthebuilder/resolve-flatpak#37]
flatpak build-bundle repo not working 

after that command  i was waiting forever and nothing happen

**Comment by koloved** [comment]
i tried installed instead bundle - flatpak-builder --user --install --force-clean build-dir com.blackmagic.Resolve.yaml

wont start cause - error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory

**Comment by koloved** [comment]
> Have the same issue, aren't there any updates?

you can install bazzite, its contain davinci auto installer

**Comment by KOVYRDLO** [comment]
another os just for davinci? Maybe later

**Comment by pobthebuilder** [comment]
Dup of #27
