### ISSUE TITLE
feature request: wayland support

### ISSUE THREAD

**Issue by TheRsKing** [pobthebuilder/resolve-flatpak#45]
https://www.reddit.com/r/davinciresolve/comments/1c397ss/amazing_news_davinci_resolve_19_has_full_wayland/ with davinci resolve 19 the wayland support came in. but i couldn't get it to start with your great flatpak. Any plans to add this?

_and just a quick question, do you not publish bundles in the releases section for copyright reasons? because that would save many people a lot of time ;)_

**Comment by Twig6943** [comment]
> https://www.reddit.com/r/davinciresolve/comments/1c397ss/amazing_news_davinci_resolve_19_has_full_wayland/ with davinci resolve 19 the wayland support came in. but i couldn't get it to start with your great flatpak. Any plans to add this?
> 
> _and just a quick question, do you not publish bundles in the releases section for copyright reasons? because that would save many people a lot of time ;)_

@TheRsKing does it use the wayland backend when you use a pkg other than flatpak? (that reddit post seems to be misinfo)

**Comment by TheRsKing** [comment]
you are right, thanks and sorry ;)
