### ISSUE TITLE
Error loading desktop file: Failed to find icon: Failed to find icon com.blackmagic.Resolve

### ISSUE THREAD

**Issue by UuBroot** [pobthebuilder/resolve-flatpak#6]
While running flatpak-builder --force-clean --repo=repo build-dir com.blackmagic.Resolve.yaml it throws that error and crashes.
I'm running Fedora Silverblue 38 with a Fedora 37 Toolbox

The Output:
➜  resolve-flatpak git:(main) ✗ flatpak-builder --force-clean --repo=repo build-dir com.blackmagic.Resolve.yaml
Emptying app dir 'build-dir'
Downloading sources
Starting build of com.blackmagic.Resolve
Cache hit for glu, skipping build
Cache hit for resolve, skipping build
Cache miss, checking out last cache hit
Cleaning up
Removing files/lib/pkgconfig/glu.pc
Removing files/lib/pkgconfig
Removing files/lib/libGLU.la
Removing files/include/GL/glu.h
Removing files/include/GL
Removing files/include
Renaming com.blackmagic.Resolve.metainfo.xml to share/appdata/com.blackmagic.Resolve.appdata.xml
Running appstream-compose
Processing application com.blackmagic.Resolve
Error loading desktop file: Failed to find icon: Failed to find icon com.blackmagic.Resolve
Error: ERROR: appstream-compose failed: Child process exited with code 1

**Comment by pobthebuilder** [comment]
i don't get this issue here. did the build crash and restart? clean up and clone again and rebuild?
